permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet #kramdown  #redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]

gems: [jekyll-paginate]
paginate: 10
paginate_path: ":num"
baseurl: ""

encoding: utf-8


title: "Yurnero"
email: "zhangcunli8499@126.com"
description: "并非所有流浪者都迷失了自我!"
github_username:  "zhangcunli"
#swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
swiftype_searchId: "5MicZLzWNxdP9sZAbqgz"
disqus_shortname: "zhangcunligithubio"

url: "http://zhangcunli.github.io"
imgrepo: "http://zhangcunli.github.io/static/img"
#url: "http://10.10.8.12:4000"
#imgrepo: "http://10.10.8.12:4000/static/img"
