# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yurnero Github Blog
email: zhangcunli8499@126.com
description: > # this means to ignore newlines until "baseurl:"
  并非所有流浪者都迷失了自我!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhangcunli.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  zhangcunli

# Build settings
markdown: kramdown
